In [2]:
## Standard libraries
import os
import json
import math
import numpy as np
import time

In [4]:
! pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
! pip install -q torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
! pip install -q torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu113.html
! pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113


In [4]:
import requests
requests.packages.urllib3.disable_warnings()
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context

In [5]:
import keras
from keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [6]:
X_train_norm = tf.keras.utils.normalize(X_train, axis=1)

In [7]:
arr = np.array([[1, 2], [4, 5], [7, 8]])
arr_norm_axis0 = tf.keras.utils.normalize(arr, axis=0)
arr_norm_axis1  = tf.keras.utils.normalize(arr, axis=1)
print("arr \n", arr)
print("arr_norm_axis0 \n", arr_norm_axis0)
print("arr_norm_axis1 \n", arr_norm_axis1) 


arr 
 [[1 2]
 [4 5]
 [7 8]]
arr_norm_axis0 
 [[0.12309149 0.20739034]
 [0.49236596 0.51847585]
 [0.86164044 0.82956136]]
arr_norm_axis1 
 [[0.4472136  0.89442719]
 [0.62469505 0.78086881]
 [0.65850461 0.75257669]]


# Tạo model 


In [10]:
model = tf.keras.models.Sequential()
# model.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=(28, 28, 1)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(10, activation=tf.nn.softmax))


In [13]:
model.compile(optimizer = "adam", loss = "sparse_category_crossentropy",  
                    metrics = ["accuracy"] # what to track - những gì để theo dõi sẽ được lưu ở đây
                    )

model.compile(optimizer='adam',  # Good default optimizer to start with
				loss='sparse_categorical_crossentropy',  # how will we calculate our "error." Neural network aims to minimize loss.
				metrics=['accuracy'])  # what to track

hist  = model.fit(X_train, y_train, epochs=3, batch_size = 1024 )  # train the model
val_loss, val_acc = hist.history['loss'][-1], hist.history['accuracy'][-1]
print("val_loss, val_acc \n", val_loss, val_acc)

Epoch 1/3
59/59 [==============================] - 1s 3ms/step - loss: 0.4102 - accuracy: 0.9593
Epoch 2/3
59/59 [==============================] - 0s 3ms/step - loss: 0.2598 - accuracy: 0.9678
Epoch 3/3
59/59 [==============================] - 0s 3ms/step - loss: 0.1898 - accuracy: 0.9732
val_loss, val_acc 
 0.18979400396347046 0.9732333421707153


In [15]:
hist.history["accuracy"]

[0.9592666625976562, 0.9678000211715698, 0.9732333421707153]

In [14]:
val_loss, val_acc = model.evaluate(X_test, y_test) # return loss and accuracy in test data

print("val_loss, val_acc \n", val_loss, val_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.6202 - accuracy: 0.9482
val_loss, val_acc 
 0.6201717853546143 0.948199987411499


# SỬ DỤNG WANDB


In [1]:
import wandb
wandb.init(project = "xanh_geo")

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: aiotlab (use `wandb login --relogin` to force relogin)


In [1]:
import wandb 
wandb.init(project="xanh_geo")

Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: longnd (aiotlab). Use `wandb login --relogin` to force relogin


Problem at: /tmp/ipykernel_43097/433715411.py 2 <cell line: 2>


KeyboardInterrupt: 

Exception in thread StatsThr:
Traceback (most recent call last):
  File "/mnt/disk1/doan/.conda/envs/blister_packs/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/mnt/disk1/doan/.conda/envs/blister_packs/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/disk1/doan/.conda/envs/blister_packs/lib/python3.9/site-packages/wandb/sdk/internal/stats.py", line 126, in _thread_body
    stats = self.stats()
  File "/mnt/disk1/doan/.conda/envs/blister_packs/lib/python3.9/site-packages/wandb/sdk/internal/stats.py", line 172, in stats
    handle = pynvml.nvmlDeviceGetHandleByIndex(i)
  File "/mnt/disk1/doan/.conda/envs/blister_packs/lib/python3.9/site-packages/wandb/vendor/pynvml/pynvml.py", line 819, in nvmlDeviceGetHandleByIndex
    _nvmlCheckReturn(ret)
  File "/mnt/disk1/doan/.conda/envs/blister_packs/lib/python3.9/site-packages/wandb/vendor/pynvml/pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLErr

In [ ]:
wandb.finish()